FROM ubuntu:trusty

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=acunar/acunar
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY acunar.tar.gz /acunar.tar.gz
RUN tar -xvf /acunar.tar.gz

#xenial
#Missing requirement: libtool
#RUN apt install -yqq libtool-bin
RUN cd /acunar/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /acunar && scripts/windows-crosscompile/compile-acunar.sh
